#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate dict/emoji_keys.txt — offline EN+AR keyword index for emoji search.
Format: emoji \t kw1,kw2,...   (keywords lowercase; Arabic entries kept raw,
normalization happens at load time in EmojiRepo). Every emoji in emoji.txt is
covered: curated keywords when available, category fallback always appended."""
import os

ASSETS = "/home/z/my-project/DRSKeyboard/app/src/main/assets/dict"
SRC = os.path.join(ASSETS, "emoji.txt")
DST = os.path.join(ASSETS, "emoji_keys.txt")

# Curated keywords per emoji (EN + AR). Anything not listed here still gets
# its category fallback words, so search covers all 999 emoji.
K = {
 # ---- smileys ----
 "😀": "grin,happy,smile,ابتسامة,سعيد,فرح",
 "😃": "smile,happy,joy,ابتسامة,سعادة,فرح",
 "😄": "smile,laugh,happy,ضحك,سعيد,فرح",
 "😁": "grin,beam,smile,ابتسامة,ضحكة",
 "😆": "laugh,lol,squint,ضحك,قهقهة",
 "😅": "sweat,laugh,relief,عرق,ضحك,ارتياح",
 "🤣": "lol,laugh,rofl,ضحك,مقعد,قهقهة",
 "😂": "lol,laugh,tears,joy,ضحك,دموع,فرح",
 "🙂": "smile,slight,ابتسامة",
 "🙃": "upside,down,silly,مقلوب,مرح",
 "😉": "wink,flirt,غمزة,غمز",
 "😊": "blush,shy,happy,خجل,ابتسامة,سعادة",
 "😇": "angel,halo,innocent,ملاك,بريء",
 "🥰": "love,hearts,adore,حب,عشق",
 "😍": "heart,eyes,love,حب,عيون,هيام",
 "🤩": "star,struck,wow,دهشة,إعجاب,نجمة",
 "😘": "kiss,بوسة,قبلة,حب",
 "😗": "kiss,قبلة,بوسة",
 "😚": "kiss,قبلة,بوسة",
 "😙": "kiss,قبلة,بوسة",
 "🥲": "tear,sad,happy,دمعة,حزن",
 "😋": "yum,tasty,tongue,لذيذ,شهية,لسان",
 "😛": "tongue,لسان,مرح",
 "😜": "wink,tongue,crazy,غمزة,لسان,هبل",
 "🤪": "zany,crazy,wacky,مجنون,هبل",
 "😝": "tongue,squint,لسان,مرح",
 "🤑": "money,face,rich,مال,ثري,طمع",
 "🤗": "hug,عناق,حضن,حب",
 "🤭": "oops,hand,giggle,شهقة,ضحك,خجل",
 "🤫": "shush,quiet,secret,سسكوت,هدوء,سر",
 "🤔": "think,think,hmm,تفكير,تفكر,همم",
 "🤐": "zip,quiet,mouth,سكوت,فم",
 "🤨": "eyebrow,suspect,شك,حاجب",
 "😐": "neutral,blank,محايد,ملل",
 "😑": "expressionless,blank,ملل,فراغ",
 "😶": "silent,mouthless,سكوت,صمت",
 "😏": "smirk,sly,سخرية,ملامحة",
 "😒": "unamused,bored,ملل,ضيق",
 "🙄": "eyeroll,annoyed,ضيق,تدحرج",
 "😬": "grimace,awkward,حرج,توتر",
 "🤥": "lie,pinocchio,كذب,كذاب",
 "😌": "relief,calm,ارتياح,هدوء",
 "😔": "pensive,sad,حزن,كآبة",
 "😪": "sleepy,tired,نعاس,تعب,نوم",
 "🤤": "drool,لعاب,شهية",
 "😴": "sleep,zzz,نوم,نائم",
 "😷": "mask,sick,كمامة,مرض",
 "🤒": "thermometer,sick,حرارة,مرض",
 "🤕": "bandage,hurt,جرح,إصابة,ضماد",
 "🤢": "nausea,sick,غثيان,قرف",
 "🤮": "vomit,puke,تقيؤ,قرف",
 "🤧": "sneeze,عطس,زكام",
 "🥵": "hot,heat,sweat,حر,حرارة,عرق",
 "🥶": "cold,freeze,برد,تجمد",
 "🥴": "woozy,drunk,dizzy,دوخة,سكر",
 "😵": "dizzy,dead,doh,دوخة,غيبوبة",
 "🤯": "mind,blown,shock,انفجار,صدمة",
 "🤠": "cowboy,hat,كاوبوي,قبعة",
 "🥳": "party,celebrate,حفلة,احتفال,فرح",
 "🥸": "disguise,incognito,تنكر,مقنع",
 "😎": "cool,sunglasses,واثق,نظارة,رائع",
 "🤓": "nerd,glasses,محشش,نظارة",
 "🧐": "monocle,inspect,تدقيق,فحص",
 "😕": "confused,حيرة,حيران",
 "😟": "worried,قلق,هم",
 "🙁": "frown,sad,حزن,عبوس",
 "☹️": "frown,sad,حزن,عبوس",
 "😮": "wow,surprise,مندهش,مفاجأة",
 "😯": "hushed,دهشة,صمت",
 "😲": "astonished,shock,ذهول,صدمة",
 "🥺": "pleading,beg,توسل,أبكي",
 "😳": "flushed,embarrassed,خجل,إحراج",
 "😦": "frown,confused,عبوس,حيرة",
 "😧": "anguished,قلق,ضيق",
 "😨": "fearful,scared,خوف,رهبة",
 "😰": "anxious,sweat,قلق,توتر",
 "😥": "sad,relieved,حزن,ارتياح",
 "😢": "cry,tear,بكاء,دمعة",
 "😭": "sob,cry,bawling,بكاء,صراخ,دموع",
 "😱": "scream,fear,صراخ,خوف,رعب",
 "😖": "confounded,ضيق,انزعاج",
 "😣": "persevere,صراع,تحمل",
 "😞": "disappointed,خيبة,حزن",
 "😓": "downcast,sweat,عرق,ضيق",
 "😩": "weary,tired,تعب,إنهاك",
 "😫": "tired,exhausted,تعب,إنهاك",
 "🥱": "yawn,bored,تثاؤب,ملل,نعاس",
 "😤": "triumph,steam,غضب,حماس",
 "😡": "rage,angry,غضب,غاضب",
 "😠": "angry,mad,غضب,غاضب",
 "🤬": "swear,cursing,شتم,سباب",
 "🤯": "mindblown,shock,انفجار,صدمة",
 "😈": "devil,imp,شيطان,مكر",
 "👿": "imp,angry,devil,شيطان,غضب",
 "💀": "skull,dead,جمجمة,موت",
 "☠️": "skull,bones,dead,جمجمة,عظام,خطر",
 "💩": "poop,براز,فضلات",
 "🤡": "clown,مهرج",
 "👻": "ghost,شبح,طيف",
 "👽": "alien,فضائي,كائن",
 "🤖": "robot,روبوت,آلي",
 "🎃": "halloween,pumpkin,يالوين,قرع",
 "😺": "cat,smile,قطة,ابتسامة",
 "😹": "cat,laugh,قطة,ضحك",
 "😻": "cat,love,heart,قطة,حب",
 "😼": "cat,smirk,قطة,سخرية",
 "😽": "cat,kiss,قطة,قبلة",
 "🙀": "cat,shock,قطة,دهشة",
 "😿": "cat,sad,cry,قطة,حزن,بكاء",
 "😾": "cat,pouting,قطة,غضب",
 # ---- people ----
 "👋": "wave,hi,hello,bye,مرحبا,سلام,وداع,تلويح",
 "🤚": "hand,raised,يد,رفع",
 "🖐️": "hand,fingers,يد,أصابع",
 "✋": "hand,stop,hi,يد,توقف,مرحبا",
 "🖖": "spock,vulcan,سابق,تحية",
 "👌": "ok,perfect,تمام,ممتاز,جيد",
 "🤌": "pinch,italian,قرصة",
 "🤏": "pinch,small,قرصة,صغير",
 "✌️": "victory,peace,peace,نصر,سلام,فوز",
 "🤞": "fingers,crossed,luck,حظ,تمني",
 "🤟": "love,you,حب,إشارة",
 "🤘": "rock,horns,روك,قرون",
 "🤙": "call,shaka,اتصال,مكالمة",
 "👈": "point,left,يسار,إشارة",
 "👉": "point,right,يمين,إشارة",
 "👆": "point,up,finger,أعلى,إشارة",
 "🖕": "middle,finger,وسط,إهانة",
 "👇": "point,down,أسفل,إشارة",
 "☝️": "index,up,إشارة,أعلى",
 "👍": "thumbsup,like,ok,good,إعجاب,جيد,أعجبني,تمام",
 "👎": "thumbsdown,dislike,bad,عدم,سيء,لم يعجبني",
 "✊": "fist,punch,قبضة,لكمة",
 "👊": "fist,punch,bump,لكمة,قبضة",
 "🤛": "fist,left,قبضة,يسار",
 "🤜": "fist,right,قبضة,يمين",
 "👏": "clap,applause,تصفيق,تصفيق",
 "🙌": "praise,celebrate,هلا,احتفال,تمجيد",
 "👐": "open,hands,يدين,فتح",
 "🤲": "palms,up,dua,يدان,دعاء",
 "🤝": "handshake,deal,مصافحة,اتفاق",
 "🙏": "pray,thanks,please,صلاة,شكرا,رجاء,دعاء",
 "✍️": "write,hand,writing,كتابة,كتاب",
 "💅": "nails,polish,manicure,أظافر,طلاء",
 "🤳": "selfie,سيلفي,تصوير",
 "💪": "muscle,strong,flex,عضلة,قوة,قوي",
 "🦾": "arm,prosthetic,ذراع,صناعي",
 "🧠": "brain,smart,دماغ,عقل,ذكي",
 "🦵": "leg,kick,ساق,ركل",
 "🦶": "foot,قدم",
 "👂": "ear,listen,أذن,استماع",
 "👃": "nose,smell,أنف,شم",
 "🧑": "person,human,شخص,إنسان",
 "👶": "baby,رضيع,طفل,بيبي",
 "🧒": "child,kid,طفل,ولد",
 "👦": "boy,ولد,صبي",
 "👧": "girl,بنت,فتاة",
 "🧑": "person,شخص",
 "👨": "man,رجل",
 "👩": "woman,امرأة,ست",
 "🧓": "older,person,مسن,كبير",
 "👴": "old,man,جد,رجل مسن",
 "👵": "old,woman,جدة,امرأة مسنة",
 "🙍": "frown,person,عبوس,حزين",
 "🙎": "pouting,person,غاضب,انزعاج",
 "🙅": "no,forbid,gestre,رفض,منع,لا",
 "🙆": "ok,person,موافقة,نعم",
 "💁": "info,desk,معلومات,خدمة",
 "🙋": "raise,hand,سؤال,رفع يد",
 "🧏": "deaf,أصم,صم",
 "🙇": "bow,apologize,انحناء,اعتذار",
 "🤦": "facepalm,سمجه,إحباط,لوحة وجه",
 "🤷": "shrug,dontknow,لا أعرف,تجاهل,كتف",
 "👨‍⚕️": "doctor,طبيب,دكتور",
 "👩‍⚕️": "nurse,doctor,ممرضة,طبيبة",
 "👨‍🎓": "student,graduate,طالب,تخرج",
 "👩‍🎓": "student,graduate,طالبة,تخرج",
 "👨‍🏫": "teacher,معلم,مدرس",
 "👩‍🏫": "teacher,معلمة,مدرسة",
 "👨‍💻": "developer,coder,مبرمج,مطور",
 "👩‍💻": "developer,coder,مبرمجة,مطورة",
 "👮": "police,شرطي,بوليس",
 "🕵️": "detective,spy,مخبر,جاسوس",
 "💂": "guard,حارس",
 "👷": "worker,builder,عامل,بناء",
 "🤴": "prince,أمير,ملك",
 "👸": "princess,أميرة,ملكة",
 "👳": "turban,عمامة",
 "🤵": "tuxedo,groom,عريس,بدلة",
 "👰": "bride,wedding,عروس,زواج",
 "🤰": "pregnant,حامل",
 "🤱": "breastfeed,رضاعة",
 "👼": "angel,baby,ملاك,طفل",
 "🎅": "santa,christmas,بابا نويل,كريسمس",
 "🦸": "superhero,بطل خارق",
 "🦹": "supervillain,شرير خارق",
 "🧙": "wizard,mage,ساحر,مشعوذ",
 "🧚": "fairy,جنية",
 "🧛": "vampire,مصاص دماء",
 "🧜": "merperson,mermaid,حورية,بحر",
 "🧝": "elf,قزم",
 "🧞": "genie,جني",
 "🧟": "zombie,زومبي",
 "💃": "dancer,dance,راقصة,رقص",
 "🕺": "dancer,dance,راقص,رقص",
 "👯": "bunny,dancer,party,رقص,أرنب",
 "🧘": "yoga,meditate,يوغا,تأمل",
 "🛀": "bath,حمام,استحمام",
 "🛌": "sleep,bed,نوم,سرير",
 "🚶": "walk,مشي,يمشي",
 "🏃": "run,جري,يركض,سباق",
 "🧎": "kneel,رُكوع",
 "👨‍👩‍👧": "family,عائلة",
 "👨‍👩‍👧‍👦": "family,عائلة",
 "👩‍❤️‍👨": "couple,love,زوجان,حب",
 "💏": "kiss,couple,قبلة,بوسة",
 "💪": "strong,muscle,عضلة,قوي",
 # ---- animals ----
 "🐶": "dog,puppy,كلب,جرو",
 "🐱": "cat,kitty,قط,قطة,مزو",
 "🐭": "mouse,rat,فأر,فار",
 "🐹": "hamster,هامستر",
 "🐰": "rabbit,bunny,أرنب",
 "🦊": "fox,ثعلب",
 "🐻": "bear,دب",
 "🐼": "panda,باندا",
 "🐨": "koala,كوالا",
 "🐯": "tiger,نمر",
 "🦁": "lion,أسد",
 "🐮": "cow,bull,بقرة,ثور",
 "🐷": "pig,خنزير",
 "🐽": "pig,nose,خنزير,أنف",
 "🐸": "frog,ضفدع",
 "🐵": "monkey,face,قرد",
 "🙈": "monkey,see,evil,قرد,لا أرى",
 "🙉": "monkey,hear,قرد,لا أسمع",
 "🙊": "monkey,speak,قرد,لا أتكلم",
 "🐒": "monkey,قرد",
 "🐔": "chicken,hen,دجاجة,فرخ",
 "🐧": "penguin,بطريق",
 "🐦": "bird,طائر,عصفور",
 "🐤": "chick,bird,صوص,فرخ",
 "🦆": "duck,بطة",
 "🦅": "eagle,نسر",
 "🦉": "owl,بومة",
 "🦇": "bat,خفاش",
 "🐺": "wolf,ذئب",
 "🐗": "boar,خنزير بري",
 "🐴": "horse,حصان",
 "🦄": "unicorn,وحيد قرن",
 "🐝": "bee,نحلة",
 "🐛": "bug,caterpillar,يرقة,دودة",
 "🦋": "butterfly,فراشة",
 "🐌": "snail,حلزون",
 "🐞": "ladybug,بقلة,حشرة",
 "🐜": "ant,نملة",
 "🦗": "cricket,جرادة",
 "🕷️": "spider,عنكبوت",
 "🦂": "scorpion,عقرب",
 "🐢": "turtle,سلحفاة",
 "🐍": "snake,ثعبان,حية",
 "🦎": "lizard,سحلية",
 "🦖": "trex,dinosaur,ديناصور",
 "🦕": "dinosaur,ديناصور",
 "🐙": "octopus,أخطبوط",
 "🦑": "squid,حبار",
 "🦐": "shrimp,روبيان,جمبري",
 "🦀": "crab,سلطعون",
 "🐡": "blowfish,سمكة منتفخة",
 "🐠": "fish,tropical,سمكة استوائية",
 "🐟": "fish,سمكة",
 "🐬": "dolphin,دولفين,دلفين",
 "🐳": "whale,حوت",
 "🦈": "shark,قرش",
 "🐊": "crocodile,تمساح",
 "🐅": "tiger,نمر",
 "🐆": "leopard,فهد",
 "🦓": "zebra,حمار وحشي",
 "🦍": "gorilla,غوريلا",
 "🐘": "elephant,فيل",
 "🦏": "rhino,وحيد القرن",
 "🐪": "camel,جمل",
 "🐫": "camel,جمل",
 "🦒": "giraffe,زرافة",
 "🐃": "buffalo,جاموس",
 "🐄": "cow,بقرة",
 "🐎": "horse,حصان",
 "🐖": "pig,خنزير",
 "🐏": "ram,كبش",
 "🐑": "sheep,خروف,غنم",
 "🐐": "goat,ماعز",
 "🦌": "deer,غزال,أيل",
 "🐕": "dog,كلب",
 "🐩": "poodle,كلب بودل",
 "🦮": "guide,dog,كلب مرشد",
 "🐈": "cat,قطة",
 "🐓": "rooster,ديك",
 "🦃": "turkey,رومي,ديك رومي",
 "🦚": "peacock,طاووس",
 "🦜": "parrot,ببغاء",
 "🦢": "swan,بجعة",
 "🕊️": "dove,peace,حمامة,سلام",
 "🐇": "rabbit,أرنب",
 "🦝": "raccoon,راكون",
 "🦨": "skunk,ظربان",
 "🦥": "sloth,كسلان",
 "🦦": "otter,قضاعة",
 "🐾": "paws,tracks,آثار,قدم حيوان",
 # ---- food ----
 "🍏": "apple,green,تفاح أخضر,تفاح",
 "🍎": "apple,تفاح",
 "🍐": "pear,كمثرى",
 "🍊": "orange,mandarin,برتقال,ماندرين",
 "🍋": "lemon,ليمون",
 "🍌": "banana,موز",
 "🍉": "watermelon,بطيخ",
 "🍇": "grapes,عنب",
 "🍓": "strawberry,فراولة",
 "🫐": "blueberries,توت أزرق",
 "🍈": "melon,شمام,كنتالوب",
 "🍒": "cherries,كرز,حبوب",
 "🍑": "peach,خوخ",
 "🥭": "mango,مانجو",
 "🍍": "pineapple,أناناس",
 "🥥": "coconut,جوز الهند",
 "🥝": "kiwi,كيوي",
 "🍅": "tomato,طماطم,بندورة",
 "🍆": "eggplant,باذنجان",
 "🥑": "avocado,أفوكادو",
 "🥦": "broccoli,بروكلي",
 "🥬": "greens,lettuce,خس,ورقيات",
 "🥒": "cucumber,خيار",
 "🌶️": "pepper,hot,فلفل حار",
 "🌽": "corn,ذرة",
 "🥕": "carrot,جزرة",
 "🧄": "garlic,ثوم",
 "🧅": "onion,بصل",
 "🥔": "potato,بطاطس,بطاطا",
 "🍠": "sweet,potato,بطاطا حلوة",
 "🥐": "croissant,كرواسون",
 "🥯": "bagel,بيغل",
 "🍞": "bread,خبز",
 "🥖": "baguette,بغيط,خبز",
 "🥨": "pretzel,برتزل",
 "🧀": "cheese,جبن,جبنة",
 "🥚": "egg,بيض,بيضة",
 "🍳": "egg,cooking,فريتاتا,بيض مقلي,طبخ",
 "🧇": "waffle,وافل",
 "🥞": "pancakes,بان كيك,فطائر",
 "🥓": "bacon,لحم مقدد",
 "🥩": "steak,meat,ستيك,لحم",
 "🍗": "chicken,leg,دجاج,ورك دجاج",
 "🍖": "meat,bone,لحم بعظم",
 "🌭": "hotdog,هوت دوج",
 "🍔": "burger,hamburger,برجر,همبرجر",
 "🍟": "fries,بطاطس مقلية",
 "🍕": "pizza,بيتزا",
 "🥙": "pita,flatbread,بيتا,خبز",
 "🥪": "sandwich,ساندويتش",
 "🥫": "can,soup,علبة,شوربة",
 "🌮": "taco,تاكو",
 "🌯": "burrito,بوريتو",
 "🥗": "salad,سلطة",
 "🥘": "paella,pan,طاجن,قدر",
 "🍝": "spaghetti,pasta,مكرونة,سباغيتي",
 "🍜": "noodles,ramen,نودلز,رامن",
 "🍲": "stew,soup,شوربة,طبق",
 "🍛": "curry,rice,كاري,أرز",
 "🍣": "sushi,سوشي",
 "🍱": "bento,بنتو",
 "🥟": "dumpling,زلابية محشية",
 "🍤": "shrimp,fried,جمبري مقلي",
 "🍙": "rice,ball,أرز كرة",
 "🍚": "rice,أرز",
 "🍥": "fish,cake,عجينة سمك",
 "🥠": "fortune,cookie,كعكة الحظ",
 "🥮": "moon,cake,كعكة القمر",
 "🍢": "skewer,كباب,سيخ",
 "🍡": "dango,دونغو",
 "🍧": "shaved,ice,ثلج مبشور",
 "🍨": "icecream,ice cream,بوظة,آيس كريم",
 "🍦": "soft,serve,icecream,بوظة,آيس كريم",
 "🥧": "pie,فطيرة",
 "🧁": "cupcake,كب كيك",
 "🍰": "cake,كيك,حلويات",
 "🎂": "birthday,cake,عيد ميلاد,كيك",
 "🍮": "custard,crème,كريمة,مهلبية",
 "🍭": "lollipop,سكر لولو,حلوى",
 "🍬": "candy,حلوى,سكر",
 "🍫": "chocolate,شوكولاتة",
 "🍿": "popcorn,فشار",
 "🍩": "donut,doughnut,دونات",
 "🍪": "cookie,كوكيز,بسكويت",
 "☕": "coffee,قهوة,كافيين",
 "🍵": "tea,شاي",
 "🥤": "soda,cup,عصير,مشروب,كوب",
 "🧃": "juice,box,عصير",
 "🧉": "mate,شاي الميت",
 "🥛": "milk,حليب",
 "🍺": "beer,بيرة",
 "🍻": "beers,cheers,بيرة,في صحتك",
 "🥂": "champagne,toast,شمبانيا",
 "🍷": "wine,نبيذ",
 "🥃": "whisky,ويسكي",
 "🍸": "cocktail,كوكتيل",
 "🍹": "tropical,drink,مشروب استوائي",
 "🧂": "salt,ملح",
 "🥄": "spoon,ملعقة",
 "🍴": "fork,knife,شوكة,سكين",
 "🍽️": "plate,food,طبق,أكل,وجبة",
 "🥢": "chopsticks,عيدان",
 "🍯": "honey,عسل",
 # ---- activity ----
 "⚽": "soccer,football,كرة قدم",
 "🏀": "basketball,كرة سلة",
 "🏈": "football,كرة أمريكية",
 "⚾": "baseball,بيسبول",
 "🥎": "softball,كرة لينة",
 "🎾": "tennis,تنس",
 "🏐": "volleyball,كرة طائرة",
 "🏉": "rugby,رغبي",
 "🥏": "frisbee,فريسبي",
 "🎱": "billiards,pool,بلياردو",
 "🏓": "pingpong,table tennis,تنس طاولة",
 "🏸": "badminton,ريشة",
 "🥊": "boxing,ملاكمة",
 "🥋": "martial,arts,فنون قتالية",
 "🥅": "goal,net,مرمى,شبكة",
 "⛳": "golf,غولف",
 "⛸️": "skate,ice,تزلج جليدي",
 "🎣": "fishing,صيد سمك",
 "🤿": "diving,غطس",
 "🎽": "running,shirt,قميص رياضي",
 "🎿": "ski,تزلج",
 "🛷": "sled,زلاجة",
 "🥌": "curling,كيرلنج",
 "🎯": "target,dart,bullseye,هدف,سهام,دقة",
 "🪀": "yo-yo,يويو",
 "🪁": "kite,طائرة ورقية,ورق",
 "🔫": "water,pistol,مسدس ماء",
 "🎱": "pool,8ball,بلياردو",
 "🎮": "game,controller,لعبة,تحكم,جيمنج",
 "🕹️": "joystick,game,عصا تحكم,ألعاب",
 "🎲": "dice,game,نرد,لعبة",
 "🧩": "puzzle,لغز,بازل",
 "♟️": "chess,pawn,شطرنج",
 "🎳": "bowling,بولينج",
 "🚴": "bike,cycling,دراجة,سباق",
 "🏋️": "weightlifting,gym,رفع أثقال,جيم",
 "🤸": "cartwheel,gymnast,جمباز",
 "🤼": "wrestling,مصارعة",
 "⛹️": "basketball,player,كرة سلة",
 "🤺": "fencing,مبارزة",
 "🏇": "horse,racing,سباق خيل",
 "🧗": "climbing,تسلق",
 "🏄": "surfing,تزلج على الماء",
 "🏊": "swimming,سباحة",
 "🤾": "handball,كرة يد",
 "🏇": "horse,race,سباق",
 "🏆": "trophy,win,كأس,فوز,جائزة",
 "🥇": "gold,medal,first,ذهبية,أول,ميدالية",
 "🥈": "silver,medal,second,فضية,ثاني",
 "🥉": "bronze,medal,third,برونزية,ثالث",
 "🎖️": "medal,military,وسام,ميدالية",
 "🎗️": "ribbon,remembrance,شريط",
 "🎫": "ticket,تذكرة",
 "🎟️": "tickets,تذاكر",
 "🎭": "theater,arts,مسرح,فنون",
 "🎨": "art,paint,فن,رسم,لوحة",
 "🎪": "circus,سيرك",
 "🎤": "microphone,sing,مايك,غناء",
 "🎧": "headphones,music,سماعات,موسيقى",
 "🎼": "music,score,نوتة موسيقية",
 "🎹": "piano,بيانو",
 "🥁": "drum,طبلة,درام",
 "🎷": "saxophone,ساكسفون",
 "🎺": "trumpet,بوق",
 "🎸": "guitar,قيثارة,جيتار",
 "🪕": "banjo,بانجو",
 "🎻": "violin,كمان",
 "🎬": "clapper,movie,فيلم,سينما",
 "🎤": "sing,karaoke,غناء,كاريوكي",
 "🎯": "target,هدف",
 "🎳": "bowling,بولينج",
 "🎮": "gaming,controller,ألعاب",
 "🎲": "dice,نرد",
 "🧩": "puzzle,بازل",
 # ---- travel ----
 "🚗": "car,سيارة",
 "🚕": "taxi,تاكسي",
 "🚙": "suv,car,سيارة دفع رباعي",
 "🚌": "bus,باص,حافلة",
 "🚎": "trolley,bus,ترولي باص",
 "🏎️": "racing,car,سيارة سباق",
 "🚓": "police,car,شرطة",
 "🚑": "ambulance,إسعاف",
 "🚒": "firetruck,إطفاء",
 "🚐": "van,فان",
 "🛻": "pickup,بيك أب",
 "🚚": "truck,شاحنة",
 "🚛": "truck,trailer,شاحنة مقطورة",
 "🚜": "tractor,جرار",
 "🛴": "scooter,سكوتر",
 "🚲": "bicycle,bike,دراجة هوائية",
 "🛵": "scooter,motor,دراجة نارية",
 "🏍️": "motorcycle,دراجة نارية,موتوسيكل",
 "🚨": "police,light,emergency,شرطة,إنذار,طوارئ",
 "🚔": "police,car,شرطة",
 "🚍": "bus,باص",
 "🚘": "car,سيارة",
 "🚖": "taxi,تاكسي",
 "🚡": "aerial,tramway,تلفريك",
 "🚠": "mountain,cableway,تلفريك جبلي",
 "🚟": "suspension,railway,قطاع معلق",
 "🚃": "railway,car,قطار",
 "🚋": "tram,ترام",
 "🚞": "mountain,railway,قطار جبلي",
 "🚝": "monorail,مونوريل",
 "🚄": "bullet,train,قطار سريع",
 "🚅": "bullet,train,قطار سريع",
 "🚈": "railway,قطار",
 "🚂": "locomotive,train,قطار بخاري",
 "🚆": "train,قطار",
 "🚇": "metro,subway,مترا,مترو",
 "🚊": "tram,ترام",
 "🚉": "station,محطة",
 "✈️": "airplane,flight,طائرة,سفر,رحلة",
 "🛫": "takeoff,departure,إقلاع,سفر",
 "🛬": "landing,arrival,هبوط,وصول",
 "🛩️": "small,airplane,طائرة صغيرة",
 "💺": "seat,مقعد",
 "🛰️": "satellite,قمر صناعي",
 "🚀": "rocket,launch,صاروخ,إطلاق",
 "🛸": "ufo,flying saucer,طبق طائر",
 "🚁": "helicopter,هليكوبتر,طائرة عمودية",
 "🚟": "railway,قطار معلق",
 "⛵": "sailboat,قارب شراعي",
 "🚤": "speedboat,قارب سريع",
 "🛥️": "motor,boat,قارب",
 "🛳️": "passenger,ship,باخرة",
 "⛴️": "ferry,عبارة",
 "🚢": "ship,سفينة",
 "⚓": "anchor,مرساة",
 "⛽": "fuel,gas,بنزين,وقود",
 "🚧": "construction,أشغال,تحذير",
 "🚦": "traffic,light,إشارة مرور",
 "🚥": "traffic,light,إشارة",
 "🗺️": "map,خريطة",
 "🗿": "statue,moai,تمثال",
 "🗽": "statue,liberty,تمثال الحرية",
 "🗼": "tower,tokyo,برج,طوكيو",
 "🏰": "castle,قلعة,قصر",
 "🏯": "japanese,castle,قلعة يابانية",
 "🏟️": "stadium,ملعب,استاد",
 "🎡": "ferris,wheel,عجلة فيريس",
 "🎢": "roller,coaster,أفعوانية",
 "🎠": "carousel,horse,ميزة دوارة",
 "⛲": "fountain,نافورة",
 "⛱️": "beach,umbrella,شمسية,شاطئ",
 "🏖️": "beach,شاطئ",
 "🏝️": "island,جزيرة",
 "🏜️": "desert,صحراء",
 "🌋": "volcano,بركان",
 "⛰️": "mountain,جبل",
 "🏔️": "mountain,snow,جبل ثلجي",
 "🗻": "fuji,جبل فوجي",
 "🏕️": "camping,تخييم",
 "⛺": "tent,خيمة",
 "🏠": "house,home,منزل,بيت",
 "🏡": "house,garden,بيت بحديقة",
 "🏘️": "houses,حي,منازل",
 "🏚️": "derelict,house,بيت مهجور",
 "🏗️": "construction,بناء",
 "🏭": "factory,مصنع",
 "🏢": "office,building,مكتب,مبنى",
 "🏬": "store,متجر",
 "🏬": "department,store,متجر",
 "🏣": "post,office,بريد",
 "🏥": "hospital,مستشفى",
 "🏦": "bank,مصرف,بنك",
 "🏨": "hotel,فندق",
 "🏪": "convenience,store,متجر صغير",
 "🏫": "school,مدرسة",
 "🏛️": "classical,building,مبنى كلاسيكي",
 "💒": "wedding,زواج",
 "🕌": "mosque,مسجد",
 "🕋": "kaaba,مكة,الكعبة",
 "🛕": "temple,معبد",
 "🕍": "synagogue,معبد يهودي",
 "⛩️": "shrine,معبد",
 "🛤️": "railway,track,سكة حديد",
 "🛣️": "highway,طريق سريع",
 "🚏": "bus,stop,موقف باص",
 "🚦": "signal,traffic,إشارة",
 "🗻": "mountain,فوجي",
 "🧭": "compass,بوصلة",
 "🛫": "departure,سفر",
 "⛽": "fuel,بنزين",
 # ---- objects ----
 "⌚": "watch,time,ساعة",
 "📱": "phone,mobile,جوال,هاتف,موبايل",
 "📲": "phone,call,اتصال,هاتف",
 "💻": "laptop,computer,لابتوب,حاسوب,كمبيوتر",
 "⌨️": "keyboard,لوحة مفاتيح,كيبورد",
 "🖥️": "desktop,computer,شاشة,حاسوب",
 "🖨️": "printer,طابعة",
 "🖱️": "mouse,computer,فأرة",
 "💽": "disk,قرص",
 "💾": "floppy,disk,save,حفظ,قرص",
 "💿": "cd,disk,قرص",
 "📀": "dvd,قرص",
 "🧮": "abacus,calculator,حساب,منتق",
 "🎥": "camera,movie,كاميرا,تصوير",
 "📷": "camera,photo,كاميرا,صورة",
 "📹": "video,camera,فيديو",
 "📼": "vhs,tape,شريط",
 "🔍": "search,magnifier,zoom,بحث,عدسة,تكبير",
 "🔎": "search,magnifier,بحث,عدسة",
 "🕯️": "candle,شمعة",
 "💡": "idea,light,فكرة,ضوء,لمبة",
 "🔦": "flashlight,torch,كشاف",
 "🏮": "lantern,فانوس",
 "📔": "notebook,decorated,دفتر",
 "📕": "book,closed,كتاب,مغلق",
 "📖": "book,open,reading,كتاب مفتوح,قراءة",
 "📗": "book,green,كتاب أخضر",
 "📘": "book,blue,كتاب أزرق",
 "📙": "book,orange,كتاب برتقالي",
 "📚": "books,كتب,مكتبة",
 "📓": "notebook,دفتر",
 "📒": "ledger,دفتر",
 "📃": "page,papers,صفحة,أوراق",
 "📜": "scroll,paper,مخطوطة,ورقة",
 "📄": "document,page,مستند,صفحة",
 "📰": "newspaper,news,صحيفة,أخبار",
 "🗞️": "news,paper,أخبار",
 "📑": "bookmark,tabs,فاصل,علامة",
 "🔖": "bookmark,علامة مرجعية",
 "🏷️": "tag,label,تسمية,سعر",
 "💰": "money,bag,نقود,مال,كيس",
 "🪙": "coin,عملة,نقود",
 "💴": "yen,ين",
 "💵": "dollar,money,دولار,نقود",
 "💶": "euro,يورو",
 "💷": "pound,جنيه",
 "💸": "money,fly,إنفاق,نقود",
 "💳": "credit,card,بطاقة ائتمان,بطاقة",
 "🧾": "receipt,فاتورة,إيصال",
 "✉️": "envelope,mail,letter,ظرف,بريد,رسالة",
 "📧": "email,بريد إلكتروني",
 "📨": "mail,incoming,بريد وارد",
 "📩": "mail,بريد",
 "📤": "outbox,send,إرسال,صادر",
 "📥": "inbox,وارد",
 "📦": "package,box,صندوق,شحنة,طرود",
 "📫": "mailbox,صندوق بريد",
 "📮": "mailbox,post,بريد",
 "🗳️": "ballot,vote,تصويت,اقتراع",
 "✏️": "pencil,write,قلم,كتابة",
 "✒️": "pen,قلم",
 "🖋️": "fountain,pen,قلم حبر",
 "🖊️": "pen,قلم",
 "🖌️": "brush,paint,فرشاة,رسم",
 "🖍️": "crayon,شمع",
 "📝": "memo,note,write,مذكرة,كتابة,ملحوظة",
 "💼": "briefcase,work,حقيبة عمل,شغل",
 "📁": "folder,file,مجلد,ملف",
 "📂": "folder,open,مجلد مفتوح",
 "🗂️": "dividers,فواصل",
 "📅": "calendar,date,تقويم,تاريخ",
 "📆": "calendar,تقويم",
 "🗓️": "calendar,تقويم",
 "📇": "card,index,فهرس",
 "📈": "chart,up,growth,مخطط صاعد,نمو,ارتفاع",
 "📉": "chart,down,مخطط هابط,انخفاض",
 "📊": "chart,stats,مخطط,إحصاء",
 "📋": "clipboard,لوحة,حافظة",
 "📌": "pin,dabble,دبوس,تثبيت",
 "📍": "location,pin,موقع,دبوس",
 "📎": "paperclip,مشبك,كليب",
 "🔗": "link,chain,رابط,سلسلة",
 "🗝️": "key,old,مفتاح",
 "🔑": "key,مفتاح",
 "🔒": "lock,locked,قفل,مقفل",
 "🔓": "unlock,فتح,مفتوح",
 "🔐": "lock,secure,قفل آمن",
 "🛡️": "shield,protect,درع,حماية",
 "🧰": "toolbox,صندوق أدوات",
 "🔧": "wrench,مفتاح ربط,عدة",
 "🪛": "screwdriver,مفك",
 "🔨": "hammer,مطرقة",
 "⛏️": "pick,فأس",
 "🪚": "saw,منشار",
 "🛠️": "tools,أدوات",
 "⚙️": "gear,settings,تروس,إعدادات",
 "🧲": "magnet,مغناطيس",
 "🔫": "pistol,مسدس",
 "💊": "pill,medicine,حبة,دواء",
 "💉": "syringe,vaccine,حقنة,تطعيم",
 "🩹": "bandaid,لصقة",
 "🩺": "stethoscope,سماعة طبيب",
 "🚪": "door,باب",
 "🛏️": "bed,سرير",
 "🛋️": "sofa,كنبة,أريكة",
 "🪑": "chair,كرسي",
 "🚽": "toilet,دورة مياه,حمام",
 "🚿": "shower,دش,استحمام",
 "🛁": "bathtub,حوض استحمام",
 "🧴": "lotion,لوشن",
 "🧷": "safety,pin,دبوس أمان",
 "🧹": "broom,clean,مكنسة,تنظيف",
 "🧺": "basket,سلة",
 "🧻": "paper,towel,مناديل",
 "🪣": "bucket,دلو",
 "🧼": "soap,صابون",
 "🪥": "toothbrush,فرشاة أسنان",
 "🧽": "sponge,إسفنجة",
 "🗑️": "trash,bin,سلة مهملات,زبالة",
 "🛒": "cart,shopping,عربة تسوق",
 "🎁": "gift,present,هدية",
 "🎈": "balloon,بالون",
 "🎀": "ribbon,bow,شريط,فيونكة",
 "🪄": "magic,wand,عصا سحرية",
 "🧸": "teddy,bear,دبدوب,دمية",
 "📸": "camera,flash,كاميرا",
 "🛍️": "bags,shopping,أكياس تسوق",
 "🛎️": "bell,hotel,جرس",
 "🧳": "luggage,سفر,حقيبة",
 "⏰": "alarm,clock,منبه,ساعة",
 "⏱️": "stopwatch,ساعة إيقاف",
 "⏲️": "timer,مؤقت",
 "🕰️": "clock,ساعة حائط",
 "⌛": "hourglass,time,رمل,ساعة رملية",
 "📡": "satellite,antenna,هوائي,بث",
 "🔋": "battery,bطارية,طاقة",
 "🪫": "battery,low,بطارية ضعيفة",
 "🔌": "plug,electric,قابس,كهرباء",
 "💡": "bulb,idea,لمبة,فكرة",
 "🔋": "battery,بطارية",
 "🧯": "extinguisher,إطفاء",
 "🛢️": "oil,barrel,برميل",
 "💸": "money,نقود",
 # ---- symbols ----
 "❤️": "heart,love,red,قلب,حب,أحمر",
 "🧡": "heart,orange,قلب برتقالي",
 "💛": "heart,yellow,قلب أصفر",
 "💚": "heart,green,قلب أخضر",
 "💙": "heart,blue,قلب أزرق",
 "💜": "heart,purple,قلب بنفسجي",
 "🖤": "heart,black,قلب أسود",
 "🤍": "heart,white,قلب أبيض",
 "🤎": "heart,brown,قلب بني",
 "💔": "broken,heart,قلب مكسور,حزن",
 "❣️": "heart,exclamation,قلب",
 "💕": "two,hearts,love,قلبان,حب",
 "💞": "revolving,hearts,قلوب,حب",
 "💓": "beating,heart,قلب نابض",
 "💗": "growing,heart,قلب",
 "💖": "sparkling,heart,قلب لامع",
 "💘": "heart,arrow,cupid,قلب سهم,حب",
 "💝": "heart,ribbon,قلب وشريط",
 "💟": "heart,decoration,قلب",
 "☮️": "peace,سلام",
 "✝️": "cross,صليب",
 "☪️": "star,crescent,هلال ونجمة,إسلام",
 "🕉️": "om,أوم",
 "☸️": "dharma,دارما",
 "✡️": "star,david,نجمة داوود",
 "🔯": "star,sixpoint,نجمة سداسية",
 "🕎": "menorah,منارة",
 "☯️": "yin,yang,ين يانغ",
 "☦️": "orthodox,صليب",
 "🛐": "worship,صلاة",
 "⛎": "ophiuchus,zodiac,برج",
 "♈": "aries,zodiac,الحمل,برج",
 "♉": "taurus,zodiac,الثور,برج",
 "♊": "gemini,zodiac,الجوزاء,برج",
 "♋": "cancer,zodiac,السرطان,برج",
 "♌": "leo,zodiac,الأسد,برج",
 "♍": "virgo,zodiac,العذراء,برج",
 "♎": "libra,zodiac,الميزان,برج",
 "♏": "scorpio,zodiac,العقرب,برج",
 "♐": "sagittarius,zodiac,القوس,برج",
 "♑": "capricorn,zodiac,الجدي,برج",
 "♒": "aquarius,zodiac,الدلو,برج",
 "♓": "pisces,zodiac,الحوت,برج",
 "🆔": "id,identity,هوية",
 "⚛️": "atom,science,ذرة,علم",
 "🉑": "accept,japanese,قبول",
 "☢️": "radioactive,إشعاع",
 "☣️": "biohazard,خطر بيولوجي",
 "📴": "phone,off,إيقاف الهاتف",
 "🈶": "japanese,have,ياباني",
 "🚭": "no,smoking,ممنوع التدخين",
 "🚾": "wc,water,حمام",
 "🅰️": "a,blood,فصيلة",
 "🅱️": "b,blood,فصيلة",
 "🆎": "ab,blood,فصيلة",
 "🆑": "cl,clear,واضح",
 "🅾️": "o,blood,فصيلة",
 "🆖": "ng,خطأ",
 "🅿️": "parking,مواقف,باركنج",
 "🈲": "forbidden,ممنوع",
 "🈳": "vacancy,شاغر",
 "㊙️": "secret,سر",
 "㊗️": "congratulations,مبروك",
 "🈴": "pass,نجاح",
 "🈵": "full,ممتلئ",
 "🈹": "discount,خصم",
 "🈺": "open,فتح",
 "🈸": "application,طلب",
 "🈚": "free,مجاني",
 "🟢": "green,circle,دائرة خضراء",
 "🔴": "red,circle,دائرة حمراء",
 "🔵": "blue,circle,دائرة زرقاء",
 "🟣": "purple,circle,دائرة بنفسجية",
 "🟡": "yellow,circle,دائرة صفراء",
 "⚫": "black,circle,دائرة سوداء",
 "⚪": "white,circle,دائرة بيضاء",
 "🟥": "red,square,مربع أحمر",
 "🟧": "orange,square,مربع برتقالي",
 "🟨": "yellow,square,مربع أصفر",
 "🟩": "green,square,مربع أخضر",
 "🟦": "blue,square,مربع أزرق",
 "🟪": "purple,square,مربع بنفسجي",
 "⬛": "black,square,مربع أسود",
 "⬜": "white,square,مربع أبيض",
 "🔺": "red,triangle,مثلث أحمر",
 "🔻": "down,triangle,مثلث لأسفل",
 "🔶": "orange,diamond,معين برتقالي",
 "🔷": "blue,diamond,معين أزرق",
 "🔸": "small,orange,معين صغير",
 "🔹": "small,blue,معين أزرق",
 "💠": "diamond,dot,معين",
 "🔔": "bell,notification,جرس,تنبيه,إشعار",
 "🔕": "bell,off,silent,صامت,بدون تنبيه",
 "🎵": "music,note,موسيقى,نوتة",
 "🎶": "music,notes,موسيقى,أنغام",
 "✅": "check,done,ok,صح,تم,إكمال",
 "☑️": "check,box,مربع تحديد",
 "✔️": "check,صح,تم",
 "❌": "x,wrong,no,خطأ,لا,إلغاء",
 "❎": "x,cross,سلبي",
 "➕": "plus,add,إضافة,زائد",
 "➖": "minus,طرح,ناقص",
 "➗": "divide,قسمة",
 "✖️": "multiply,ضرب",
 "🟰": "equals,يساوي",
 "♾️": "infinity,لانهائية",
 "‼️": "exclamation,تنبيه,تعجب",
 "⁉️": "interrobang,تعجب وسؤال",
 "❓": "question,سؤال",
 "❔": "question,سؤال",
 "❕": "exclamation,تعجب",
 "❗": "exclamation,تعجب",
 "💯": "hundred,perfect,score,مئة,ممتاز,درجة",
 "💤": "sleep,zzz,نوم",
 "💫": "dizzy,star,دوخة,نجمة",
 "💦": "sweat,drops,قطرات,عرق",
 "💨": "dash,wind,رياح,انطلاق",
 "🕳️": "hole,حفرة",
 "💬": "speech,bubble,comment,فقاعة كلام,تعليق,رسالة",
 "👁️‍🗨️": "eye,bubble,witness,عين,شهادة",
 "🗨️": "speech,bubble,كلام",
 "🗯️": "anger,bubble,غضب",
 "💭": "thought,bubble,تفكير,فكرة",
 "♻️": "recycle,إعادة تدوير",
 "🔱": "trident,رمح",
 "📛": "name,badge,شارة اسم",
 "🔰": "beginner,japanese,مبتدئ",
 "⚠️": "warning,caution,تحذير,خطر",
 "🚸": "children,أطفال",
 "⛔": "no,entry,ممنوع الدخول",
 "🚫": "forbidden,prohibited,ممنوع",
 "🚳": "no,bikes,ممنوع دراجات",
 "🚱": "no,water,مياه غير صالحة",
 "🔞": "18,underage,غير مناسب",
 "📵": "no,phones,ممنوع الجوال",
 "🚯": "no,littering,ممنوع رمي النفايات",
 "❗": "exclamation,تعجب",
 "🌐": "globe,world,internet,كرة أرضية,عالم,إنترنت",
 "💠": "diamond,معين",
 "Ⓜ️": "m,circle,دائرة",
 "🌀": "cyclone,إعصار",
 "💤": "zzz,sleep,نوم",
 "🏧": "atm,صرف آلي",
 "🚾": "wc,حمام",
 "♿": "wheelchair,كرسي متحرك",
 "🅿️": "parking,موقف",
 "🈹": "discount,خصم",
 "🈳": "vacancy,شاغر",
 "🈺": "open,مفتوح",
 "🈸": "apply,طلب",
 "🈴": "pass,اجتياز",
 "🈵": "full,ممتلئ",
 "🈚": "free,مجاني",
 "🈶": "have,يوجد",
 "🈲": "prohibited,ممنوع",
 "🉐": "bargain,صفقة",
 "🆚": "vs,versus,مقابل",
 "🆕": "new,جديد",
 "🆙": "up,ارتفاع",
 "🆒": "cool,رائع",
 "🆓": "free,مجاني",
 "🆗": "ok,تمام",
 "🆗": "ok,موافق",
 "🆒": "cool,بارد",
 "🆙": "level,up,مستوى",
 "🔟": "ten,عشرة",
 "🔢": "numbers,أرقام",
 "#️⃣": "hash,number,رمز,هاشتاق",
 "*️⃣": "asterisk,نجمة",
 "0️⃣": "zero,صفر",
 "1️⃣": "one,واحد",
 "2️⃣": "two,اثنان",
 "3️⃣": "three,ثلاثة",
 "4️⃣": "four,أربعة",
 "5️⃣": "five,خمسة",
 "6️⃣": "six,ستة",
 "7️⃣": "seven,سبعة",
 "8️⃣": "eight,ثمانية",
 "9️⃣": "nine,تسعة",
 "🔡": "abc,lowercase,حروف صغيرة",
 "🔢": "123,numbers,أرقام",
 "🔠": "abc,uppercase,حروف كبيرة",
 "🔣": "symbols,رموز",
 "🔤": "abc,alphabet,حروف,أبجدية",
 "🅰️": "letter,a,حرف",
 "🆎": "letter,ab,حرف",
 "🅱️": "letter,b,حرف",
 "🆑": "letter,cl,حرف",
 "🅾️": "letter,o,حرف",
 "🆖": "ng,حرف",
 "🅿️": "letter,p,حرف",
 "🈯": "japanese,ياباني",
 "🅿️": "parking,موقف سيارات",
 "🔺": "red,triangle,مثلث",
 "🆔": "identity,هوية",
 "☯️": "yin,yang,ين",
 "✳️": "asterisk,نجمة صغيرة",
 "✴️": "eightpoint,نجمة ثمانية",
 "❇️": "sparkle,توهج",
 "©️": "copyright,حقوق",
 "®️": "registered,مسجل",
 "™️": "trademark,علامة تجارية",
 "🔀": "shuffle,random,خلط,عشوائي",
 "🔁": "repeat,loop,تكرار,دوران",
 "🔂": "repeat,one,تكرار مرة",
 "▶️": "play,تشغيل",
 "⏩": "fast,forward,تقديم سريع",
 "◀️": "reverse,رجوع",
 "⏪": "rewind,إرجاع",
 "🔼": "up,button,زر لأعلى",
 "🔽": "down,button,زر لأسفل",
 "⏫": "fast,up,سريع لأعلى",
 "⏬": "fast,down,سريع لأسفل",
 "⏸️": "pause,إيقاف مؤقت",
 "⏹️": "stop,إيقاف",
 "⏺️": "record,تسجيل",
 "⏏️": "eject,إخراج",
 "🎦": "cinema,سينما",
 "🔅": "dim,low,سطوع منخفض",
 "🔆": "bright,سطوع عالي",
 "📶": "signal,bars,إشارة,شبكة",
 "🛜": "wifi,واي فاي",
 "📳": "vibration,اهتزاز",
 "🈶": "have,ياباني",
 "🈷️": "month,شهر",
 "🈸": "application,طلب",
 "🈯": "reserved,محجوز",
 "🉐": "bargain,صفقة",
 "🈹": "discount,خصم",
 "🈚": "free,مجاني",
 "🈂️": "service,خدمة",
 "🈷️": "month,شهر",
 "6️⃣": "six,ستة",
 "🔱": "trident,رمح ثلاثي",
 "⚜️": "fleur,زنبقة",
 "〰️": "wave,dash,موجة",
 "〽️": "part,alternate,تناوب",
 "🌐": "globe,إنترنت",
 "💨": "wind,رياح",
 "📡": "antenna,بث",
 "🔊": "speaker,loud,صوت مرتفع",
 "🔉": "speaker,medium,صوت متوسط",
 "🔈": "speaker,low,صوت منخفض",
 "🔇": "mute,silent,صامت,كتم",
 "📣": "megaphone,shout,مكبر صوت,هتاف",
 "📢": "loudspeaker,announce,إعلان,مكبر",
 "📯": "posthorn,بوق بريد",
 "🔔": "bell,جرس,إشعار",
 "🔕": "no,bell,صامت",
 "🎼": "music,score,موسيقى",
 "⚔️": "swords,fight,سيوف,قتال",
 "🛡️": "shield,درع",
 "🦯": "cane,blind,عصا كفيف",
 "🦼": "motorized,wheelchair,كرسي كهربائي",
 "🦽": "wheelchair,كرسي متحرك",
 "🪑": "chair,كرسي",
 "🚬": "cigarette,تدخين,سيجارة",
 "⚰️": "coffin,نعش",
 "⚱️": "urn,جرة",
 "🧿": "nazar,evil eye,عين,حسد",
 "🪬": "hamsa,خمسة",
}

FALLBACK = {
 "smileys": "smile,face,emoji,ابتسامة,وجه",
 "people": "person,hand,people,شخص,يد,بشر",
 "animals": "animal,nature,حيوان,طبيعة",
 "food": "food,drink,طعام,أكل,شراب",
 "activity": "sport,activity,game,رياضة,نشاط,لعبة",
 "travel": "travel,place,vehicle,سفر,مكان,مركبة",
 "objects": "object,thing,شيء,أداة,جسم",
 "symbols": "symbol,sign,رمز,علامة",
}

def main():
    rows = []
    seen = set()
    with open(SRC, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or "\t" not in line:
                continue
            cat, em = line.split("\t", 1)
            if em in seen:
                continue
            seen.add(em)
            kws = [K.get(em, "")] if em in K else []
            fb = FALLBACK.get(cat, "emoji,إيموجي")
            kws.append(fb)
            # note: raw emoji string itself helps paste-search
            rows.append(f"{em}\t{','.join(kws)}")
    with open(DST, "w", encoding="utf-8") as f:
        f.write("\n".join(rows) + "\n")
    print(f"wrote {len(rows)} rows -> {DST}")
    covered = sum(1 for r in rows if not r.split("\t")[1].startswith(FALLBACK.get("smileys","") ) )
    print(f"(info) rows total {len(rows)}; unique emoji {len(seen)}")

if __name__ == "__main__":
    main()
